### ISSUE TITLE
Комментарий от ментора ДЗ №5

### ISSUE THREAD

**Issue by Petergod** [VitalikOstapenko/VitalikOstapenko.github.io#4]
- у меня так отображается Ваш макет http://joxi.ru/krDx7bPhRjgYrp это все через абсолют, а если проскролить то вот http://joxi.ru/MAjpRgvSz5Wqme
- При наведении на "Entrar" "Cadastre-se" сделайте text-decoration:none , а к "Minhas Ofertas" добавьте text-decoration: underline; , чтобы красиво было Это рекомендация)  
- http://joxi.ru/RmzzvnRfpod0mO задайте лучше через before для списка 
- в signup лишний р
- http://joxi.ru/BA0Ra8ysgW0qmy
- нету формы/кнопки фейстбука, как так?))
- http://joxi.ru/l2Ze3Z7I098wmJ сделайте через псевдоклассы before/after вместо лишних див)

**Comment by VitalikOstapenko** [comment]
> * у меня так отображается Ваш макет http://joxi.ru/krDx7bPhRjgYrp это все через абсолют, а если проскролить то вот http://joxi.ru/MAjpRgvSz5Wqme

Прибил header к верху через position:fixed. Бекграунд починил.

> * При наведении на "Entrar" "Cadastre-se" сделайте text-decoration:none , а к "Minhas Ofertas" добавьте text-decoration: underline; , чтобы красиво было Это рекомендация)

text-decoration'ы добавил.

> * http://joxi.ru/RmzzvnRfpod0mO задайте лучше через before для списка 

Наверное я не совсем понял. Вы предлагаете поменять разметку или имеете в виду ul:after с бордером?
тогда получается больше и сложнее css.
Ведь вместо одного свойства:
```css
 .top-menu .prop > a {
	border-left: 1px solid #56a2dc;
 }
```
Приходится добавлять целый набор свойств, чтобы псевдо-элемент нормально выглядел:

```css
 .top-menu ul:after {
     content: "";
     display: inline-block;
     width: 0;
     height: 30px;
     /*vertical-align: middle;*/
     margin: 3px 0;
     border-right: 1px solid #56a2dc;
}
```
хотя выглядит теперь конечно более похожим на макет :thumbsup:

> * в signup лишний р

Убрал - очепятка была.

> * http://joxi.ru/BA0Ra8ysgW0qmy

А вот тут не согласен. В [задании](https://github.com/goit-fe/markup_fe2o/tree/master/lesson_05) было: "Форма должна быть отцентрирована по горизонтали __и вертикали__"

> * нету формы/кнопки фейстбука, как так?))

Кнопку фейсбука вставил.

> * http://joxi.ru/l2Ze3Z7I098wmJ сделайте через псевдоклассы before/after вместо лишних див)

Сделал. Уменьшил разметку до: 
```html
<div class="striked"><span>OU</span></div>
```
